name: Sync

on:
  schedule:
    - cron: "0 0 * * *" # Runs every 30 minutes
  workflow_dispatch: # Triggered by manual button click

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      # Step 2: Set up Git user info
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      # Step 3: Add the upstream remote (the remote repository)
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/jakubkanna/labguy-server
      # Step 4: Fetch the upstream changes
      - name: Fetch upstream
        run: |
          git fetch upstream
      # Step 5: Reset the current repository to match the upstream's main branch
      - name: Reset to upstream/main
        run: |
          git reset --hard upstream/main
      # Step 6: Push the changes to the origin (your fork)
      - name: Push changes
        run: |
          git push origin main --force
